### ISSUE TITLE
pbin chokes on generally safe characters

### ISSUE THREAD

**Issue by AnrDaemon** [ngx/pbin#10]
Characters like "#" or "…" used in the paste name, while safe for posting to IRC, will cause the app to report "invalid input".
The culprit seems to be the https://github.com/ngx/pbin/blob/master/app.py#L108 which is… let's say, far from sane.
IRC is very lenient on allowed character range, and given the purposes and usage of the application, it is likely enough to replace characters from control range (0x00-0x1F,0x7F), as well as regular (forward) slash with spaces to construct acceptable paste name.

**Comment by dwfreed** [comment]
Strictly speaking, the only characters not allowed in the last parameter of an IRC PRIVMSG/NOTICE are NULL, CR, and LF.  I doubt where the IRC relay is posted allows mIRC colors, so the ircd will strip many of the other control codes for you (and handle the color sequences properly, so you don't end up with numbers appearing in the name).  That said, since the field is supposed to be the poster's nick, and not a name for the post itself, realistically speaking the check could be more strict than it is now.  The following regex will handle all possible IRC nicks on sane networks that don't allow Unicode characters outside the ASCII subset:

```
^[a-zA-Z\[\]\\{}|`-_][a-zA-Z0-9\[\]\\{}|`\-_]*$
```

(use raw strings to avoid having to double backslash when putting this into code)

**Comment by MTecknology** [comment]
This has been dropped into place. @AnrDaemon Wanna make sure this is okay?
